#!/usr/bin/env python3
"""
png_to_rom.py — Converts a PNG image to a VHDL ROM package for the SSD1331
Pixel format: RGB565 (16 bits: RRRRR GGGGGG BBBBB)
Target resolution: 96 x 64 pixels = 6144 pixels = 12288 bytes

Usage:
    python3 png_to_rom.py image.png              # -> image_rom.vhd
    python3 png_to_rom.py image.png -o my_rom.vhd
"""

import sys
import argparse
from pathlib import Path
from PIL import Image


SCREEN_W = 96
SCREEN_H = 64
N_PIXELS = SCREEN_W * SCREEN_H   # 6144


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    """Convert an (r, g, b) pixel with 8 bits per channel to a 16-bit RGB565 word."""
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    return (r5 << 11) | (g6 << 5) | b5


def image_to_rgb565(path: Path) -> list[int]:
    """Open image, resize if necessary, and return a list of RGB565 words."""
    img = Image.open(path).convert("RGB")

    if img.size != (SCREEN_W, SCREEN_H):
        print(f"[!] Image {img.size} -> resizing to {SCREEN_W}x{SCREEN_H}")
        img = img.resize((SCREEN_W, SCREEN_H), Image.LANCZOS)

    pixels = []
    for y in range(SCREEN_H):
        for x in range(SCREEN_W):
            r, g, b = img.getpixel((x, y))
            pixels.append(rgb888_to_rgb565(r, g, b))

    return pixels


def generate_vhdl(pixels: list[int], entity_name: str) -> str:
    """Generate a VHDL package file containing the ROM as a constant."""

    lines = []
    lines.append("library ieee;")
    lines.append("use ieee.std_logic_1164.all;")
    lines.append("")
    lines.append(f"-- Auto-generated by png_to_rom.py")
    lines.append(f"-- {SCREEN_W}x{SCREEN_H} pixels, RGB565 format")
    lines.append(f"-- {N_PIXELS} entries x 16 bits")
    lines.append(f"package {entity_name}_pkg is")
    lines.append("")
    lines.append(f"    constant IMG_W      : natural := {SCREEN_W};")
    lines.append(f"    constant IMG_H      : natural := {SCREEN_H};")
    lines.append(f"    constant IMG_PIXELS : natural := {N_PIXELS};")
    lines.append("")
    lines.append(f"    type t_img_rom is array(0 to IMG_PIXELS - 1)")
    lines.append(f"        of std_logic_vector(15 downto 0);")
    lines.append("")
    lines.append(f"    constant IMG_ROM : t_img_rom := (")

    # 8 entries per line for readability
    entries = [f'x"{p:04X}"' for p in pixels]
    chunk_size = 8
    for i in range(0, len(entries), chunk_size):
        chunk = entries[i:i + chunk_size]
        separator = "," if (i + chunk_size) < len(entries) else ""
        lines.append("        " + ", ".join(chunk) + separator)

    lines.append("    );")
    lines.append("")
    lines.append(f"end package {entity_name}_pkg;")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="PNG to VHDL ROM package for SSD1331")
    parser.add_argument("image", help="Source PNG file")
    parser.add_argument("-o", "--output", help="Output VHDL file (default: <image>_rom.vhd)")
    args = parser.parse_args()

    src = Path(args.image)
    if not src.exists():
        print(f"Error: file not found: {src}")
        sys.exit(1)

    dst = Path(args.output) if args.output else src.with_name(src.stem + "_rom.vhd")
    entity_name = dst.stem  # e.g. "image_rom"

    print(f"[*] Reading {src} ...")
    pixels = image_to_rgb565(src)
    print(f"[*] {len(pixels)} pixels converted to RGB565")

    vhdl = generate_vhdl(pixels, entity_name)
    dst.write_text(vhdl)
    print(f"[+] ROM written to {dst}")
    print(f"    -> add 'use work.{entity_name}_pkg.all;' to your VHDL files")


if __name__ == "__main__":
    main()
